### ISSUE TITLE
mcmicro_INVF maps with "holes"

### ISSUE THREAD

**Issue by YJYMY** [ekaden/smt#1]
Dear SMT team,

I have multi-band, multi-shell DWI data (MB factor3; b1000 25/6; b2000 45/6;b2800 63/6)
Data merged using mrtrix command 'mrcat'
merged data were then preprocessed for: eddy, topup (with blip up/down, 2x phase reversal b0), bias field correction)

Ran fitmcmicro --bvals merged_dc_bc.bvals --bvecs merged_dc_bc.bvecs --mask merged_dc_mask.nii merged_dc_bc.nii mcmicro.nii

When inspected the 1st volume of the mcmicro map (INVF), I note there are multiple 'holes' in the map--mostly in the GM, also some  in WM. (See attached screen shot)
![mcmicro_smt problem](https://cloud.githubusercontent.com/assets/20632282/17088592/a0963ec2-5260-11e6-8852-edf8daeeb537.png)

Any idea what could have cause this and ways to fix this problem? 

many thanks

**Comment by ekaden** [comment]
This artefact is due to Gibbs ringing, particularly in the zero b-value images. Preprocessing of the DWI data with a Gibbs ringing filter mitigates this effect.
