### ISSUE TITLE
Does SMT available for MATLAB users also?

### ISSUE THREAD

**Issue by katochnitish** [ekaden/smt#6]
Dear Enrico!

Might I be asking out of the box, Does SMT available in Matlab also?

I am not used to with C++ anymore. It will be very helpful in Matlab. I am developing Conductivity tensor imaging method. For which I need volume fraction and Intra & Extra Diffusivity. SMT has that advantage over noddi. 

Please let me know if it's available.

Will be very thankful of yours

Best regards,
Nitish

**Comment by ekaden** [comment]
The MATLAB version of SMT is rather slow. We do not only provide the source code here, but also the executable binaries:

https://github.com/ekaden/smt/releases/tag/v0.3

Thus, no knowledge of C++ is required. The input and output data format is NIfTI-1, which can be read and written using, for example, the following MATLAB toolbox:

https://github.com/ekaden/nifti
