### ISSUE TITLE
--rician flag input

### ISSUE THREAD

**Issue by nagaflokhu** [ekaden/smt#7]
Hello,

Why do `fitmicrodt` and `fitmcmicro` expect a nifti image with a single volume to be passed in with the `--rician` flag? I've been wondering about this because the Rice distribution has two parameters. The `ricedebias` function's second parameter's name, `sigma`, suggests that I can pass in the `scale` output from `ricianfit`. Is this correct?

If this is the case, why do we only pass in the `scale` parameter? Is the `loc` parameter estimated again by `fitmicrodt` and `fitmicromc`?

Thank you

**Comment by ekaden** [comment]
SMT assumes Gaussian noise by default. Alternatively, a Rician noise model may be chosen, in which case the signal measurements are adjusted to reduce the Rician-noise induced bias.

There are two ways to specify the Rician noise level, either globally using a scalar value, e.g. `--rician 12.345`, or voxel by voxel using a NIfTI-1 image volume, e.g. `--rician rician_scale_smoothed.nii`.

It is *not* recommended to use the output of `ricianfit` directly. I would either use a global estimate of the noise level (over a region of interest) or a “smoothed” version of the `scale` parameter obtained by `ricianfit`. The `loc` parameter is not required by `fitmicrodt` and `fitmcmicro`.

**Comment by nagaflokhu** [comment]
Thank you
